### ISSUE TITLE
email and password

### ISSUE THREAD

**Issue by chih3b** [amhsirak/human-monitoring-system#4]
Hello,first of all thank you for your project.i disabled alert in config but i still get this:Traceback (most recent call last):
  File "/home/chiheb/Downloads/human-monitoring-system-master/main.py", line 4, in <module>
    from lib.mailer import Mailer
  File "/home/chiheb/Downloads/human-monitoring-system-master/lib/mailer.py", line 3, in <module>
    from lib.creds import EMAIL, PASSWORD
ModuleNotFoundError: No module named 'lib.creds'

**Comment by webbrain-one** [comment]
Hi @chiheb, thanks for reporting this! I’ve opened a pull request to fix the `ModuleNotFoundError` you encountered. The PR adds the missing `lib/creds.py` file and updates the import logic so the script runs smoothly even with alerts disabled. You can check out the changes here: #5. Thanks again for your feedback, and feel free to reach out if you run into anything else!
